### PR TITLE
[WIP]: Stacking of the Dataset files

### PR DESCRIPTION
**Pull request by Nageshbansal**
This PR is a part of PR #6. it adds stackbytable function

### CODE REVIEW

**Comment by Nageshbansal** [comment]
@MarconiS, can you please take a look at the following lines of code
[L163](https://github.com/NEONScience/NEON-utilities/blob/5cdb8e66d850fe7247a6e1dfc0932c725542ca07/neonUtilities/R/stackDataFilesParallel.R#L163)
[L19](https://github.com/NEONScience/NEON-utilities/blob/5cdb8e66d850fe7247a6e1dfc0932c725542ca07/neonUtilities/R/stackDataFilesParallel.R#L19)
will there be any files like sensor_position etc. ( which are mentioned in above lines) ?

**Comment by Nageshbansal** [comment]
@MarconiS, I have completed stackdatafiles function, now we can stack files using this function. Please test this function in your system also,and below are the of some screenshots of resulted files 
#### neonwranglerpy
neonwranglerpy
#### neon-utilites
neon

**Comment by Nageshbansal** [comment]
I have to add some more checks and also some other functions, then we can merge this PR

**Comment by MarconiS** [comment]
Everything looks good. Sounds good. You may need the link for the NEON sites/plots coordinates. It is held in https://www.neonscience.org/sites/default/files/All_NEON_TOS_Plots_V9_0.zip

**Pull request closed without merging**
