### PR TITLE
Cleans the pipeline

### PR DESCRIPTION
**Pull request by Nageshbansal**

### CODE REVIEW

**Comment by Nageshbansal** [comment]
@MarconiS , can you please merge this PR.
Now, the pipeline is able to download data across multiple sites and stack them.
```
from neonwranglerpy.utilities.loadByProduct import load_by_product
df = load_by_product('DP1.10098.001',['DELA','ABBY'],start_date='2019-01',end_date='',path='./',save_files=True, stacked_df=True)
```

**Comment by henrykironde** [comment]
@Nageshbansal, please rebase the PR to reflect the most recent changes from the main.

Also, you will notice that the PR will fail due to some syntax and linting tests that we have enabled.

**Comment by henrykironde** [comment]
Ignore the errors with `D104`. In fact you can go ahead and remove it from [flake8](https://github.com/Nageshbansal/neonwranglerpy/blob/c22189572346b841276724513d119fe406913f0f/.flake8#L10) .
For the rest of the errors try to remove them.

**Comment by Nageshbansal** [comment]
Done, but it is still falling because of the ```D100```, should I also remove it?

**Pull request merged**
