### PR TITLE
removed unused function rda2csv and dependency rpy2 --branch(rda2csv)

### PR DESCRIPTION
**Pull request by satsin06**

### CODE REVIEW

**Comment by ethanwhite** [comment]
You need to remove the extra commits, not just overwrite the changes, because otherwise this makes the history difficult to understand.

You can do this by checking out your `rda2csv` branch and running:

```sh
git reset --hard 38c76a1
```

This will put the branch back to the exact state (including the history) of that first commit (just make sure you're other commits are in another branch since this will get rid of them in this one).

If you have any additional changes you need to make you can `git add` the files and the add those changes to the existing commit using:

```sh
git commit --amend
```

Finally you can push the updated version of the branch to update this PR using:

```sh
git push -f origin rda2csv
```

The `-f` forces the push, which is necessary since you've rewritten the history. Doing this is fine in branches that no one else is working on.

**Comment by satsin06** [comment]
> You need to remove the extra commits, not just overwrite the changes, because otherwise this makes the history difficult to understand.
> 
> You can do this by checking out your `rda2csv` branch and running:
> 
> ```shell
> git reset --hard 38c76a1
> ```
> 
> This will put the branch back to the exact state (including the history) of that first commit (just make sure you're other commits are in another branch since this will get rid of them in this one).
> 
> If you have any additional changes you need to make you can `git add` the files and the add those changes to the existing commit using:
> 
> ```shell
> git commit --amend
> ```
> 
> Finally you can push the updated version of the branch to update this PR using:
> 
> ```shell
> git push -f origin rda2csv
> ```
> 
> The `-f` forces the push, which is necessary since you've rewritten the history. Doing this is fine in branches that no one else is working on.

Thanks for your response @ethanwhite, I just did, please check

**Review by ethanwhite — APPROVED** [review]

**Review by Nageshbansal — APPROVED** [review]

**Comment by Nageshbansal** [comment]
LGTM.

**Comment by Nageshbansal** [comment]
@satsin06 congratulations on your first PR merged :)) Welcome to the club :)

**Pull request merged**
